### ISSUE TITLE
Breakpoint in information section

### ISSUE THREAD

**Issue by melissamcewen** [masakudamatsu/colmar_academy#19]
This extra margin stood out when I was looking in Chrome dev tools responsive mode (https://developers.google.com/web/tools/chrome-devtools/device-mode/emulate-mobile-viewports) : 
![colmar_academy](https://user-images.githubusercontent.com/1251094/38912110-1be96c00-4299-11e8-874f-94ecd8de3932.png)

One thing I would look into is either making the breakpoint move from mobile to desktop sooner for this section or making the items stretch to fill the whole screen

**Comment by masakudamatsu** [comment]
We solve this issue by the use of
```
margin: 0 auto;
max-width: 608px;
```
where 608px is the sum of the image width (576px) and the side margins (16px x 2).
